---
- name: setup opestack resources
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_tasks: create-net.yaml
    - include_tasks: create-os-instances.yaml

- name: setup docker and oc client
  hosts: openshift1 openshift2 fedhost
  roles:
    - docker
    - oc_client

- name: setup openshift
  hosts: openshift1 openshift2
  roles:
    - oc_cluster_up


