---
- name: check openshift client
  stat: path=/usr/bin/oc
  register: st

- name: download openshift client
  get_url: 
     url: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
     dest: /root/osc.tar.gz
  when: not st.stat.exists

- name: extract and install
  shell: |
    mkdir /root/osc
    cd /root/osc
    tar xvfz /root/osc.tar.gz
    cp openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/bin
    cp openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/kubectl /usr/bin
  args:
    warn: false
  when: not st.stat.exists